name: "Install Apptainer"
on:
  workflow_call:
    inputs:
      apptainer_download_url:
        required: false
        type: string
        description: "The download URL for the Apptainer package"
      apptainer_version:
        required: false
        type: string
        description: "The version of Apptainer to install"
      apptainer_arch:
        required: false
        type: string
        description: "The architecture of Apptainer to install"

jobs:
  install_apptainer:
    name: "Install Apptainer"
    runs-on: ubuntu-latest
    steps:  
      - name: Install Apptainer
        shell: bash
        run: |
          set -euo pipefail
          release_arch="${${{ github.event.inputs.apptainer_arch}}:-$(dpkg --print-architecture)}"
          download_url="${${{ github.event.inputs.apptainer_download_url }}:-}"
          if [ -z "${download_url:-}" ]; then
            release_tag="${v${{ github.event.inputs.apptainer_version }}:-latest}"
            releases_url="${https://api.github.com/repos/apptainer/apptainer/releases/tags/${release_tag}"
            download_url="$(curl -ssL "${releases_url}" | grep -o -m1 'https://github[.]com.*download[/].*apptainer_.*${release_arch}.deb')"
          fi
          if [ -z "${download_url:-}" ]; then
              echo "Unable to determine download URL for Apptainer"
              exit 1
          fi
          echo "Downloading Apptainer from ${download_url}"
          curl -sSL -o apptainer.deb "${download_url}"
          echo "Updating apt cache"
          sudo apt-get update --yes --quiet
          echo "Installing Apptainer"
          sudo dpkg --install --force-depends apptainer.deb
          sudo apt-get install --fix-broken --yes --quiet
          rm -f apptainer.deb
          sudo apt-get clean --yes --quiet
          sudo rm -rf /var/lib/apt/lists/*
          printf "Installed "; apptainer --version
